import "./globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import Link from "next/link";
import Provider from "@/context/Provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <Provider >
          <nav className="text-sm flex gap-8 justify-center py-4">
            <Link href="/">home</Link>
            <Link href="/login">login</Link>
            <Link href="/dashboard">dashboard</Link>
            <Link href="/dashboard/profile">profile</Link>
          </nav>
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
